### ISSUE TITLE
troubleshoot markdown hyperlinks in description

### ISSUE THREAD

**Issue by paulchrisluke** [pcl-labs/pcl-labs#8]
this markdown isn't working 
![image](https://user-images.githubusercontent.com/5694308/112423301-eef1c480-8d64-11eb-95f6-05c21e6a320d.png)

**Comment by joeelia** [comment]
should be fixed in 26 seconds

**Comment by paulchrisluke** [comment]
do we have to change this everywhere? 
![image](https://user-images.githubusercontent.com/5694308/112423806-e77eeb00-8d65-11eb-8158-8ec5aaa22aec.png)

**Comment by joeelia** [comment]
This is fixed in product cards now too...
